### ISSUE TITLE
[DESIGN DOCUMENT] Create graphical represenation of C-IDM schema

### ISSUE THREAD

**Issue by patrick-michelberger** [patrick-michelberger/hyp#1]

**Comment by patrick-michelberger** [comment]
(optional) SHORT textual comments, e.g., on your design solutions, notation (particularly if non-standard IDM elements are used)

**Comment by theliuk** [comment]
Almost done the C-IDM schema. I have only a doubt about some "groups" that are defined in the assignment document: I can't understand if they must be considered "groups" or "multiple groups".
I posted a question on beep and I hope to get an answer as soon as possible.
There's no need to attach any textual documentation to this schema because it is very simple and follows the standard IDM notation.

**Comment by theliuk** [comment]
**Changing the term "Health Intervention Area" (Area for short) in "Department"**:

With department we mean the same concept of "Health Intervention Area", right? 
For instance:

"Department of Pediatrics", 
"Department of General Surgery" 

and so on, right?

**Comment by patrick-michelberger** [comment]
yes exactly

**Comment by theliuk** [comment]
Perfect!
