### ISSUE TITLE
[DESIGN DOCUMENT] Create graphical represenation of L-IDM schema

### ISSUE THREAD

**Issue by patrick-michelberger** [patrick-michelberger/hyp#2]

**Comment by patrick-michelberger** [comment]
(optional) SHORT textual comments, e.g., on your design solutions, notation (particularly if non-standard IDM elements are used)

**Comment by patrick-michelberger** [comment]
graphical L-IDM is finished.

**Comment by theliuk** [comment]
Patrick, I'm looking at the L-IDM, I believe that there's an error in the interpretation of the IDM language.
In "Doctors", for instance, there should be the list of Content dialogues, that are pieces of information related to the single topic (that in this case is a single doctor).
This means that, for instance, there should be, let's say, the "Curriculum" of the Doctor, some image about him and so on. By indicating the list of names of doctors you are explicitly designing a group.
Same thing for the "Department": its box shouldn't have a list of all the department of the clinic but rather the list of atomic contents that describe the single department.

**Comment by patrick-michelberger** [comment]
you're right. I've updated it.

**Comment by theliuk** [comment]
I updated the L-IDM; I simply removed some C-DA from the kind of topics "Doctor" and "Department" that simply did the job of the T-DA on the arrows.
I have some doubt about the C-DA "Doctors" in the "Department" kind of topic because it seems like it is about information that should be carried by a T-DA (and hence by a relevant relation that isn't explicit).
On wednesday there's should be tutoring and may be it's a good occasion to mark the C-IDM and L-IDM as completed.
